# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_student.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_New_Stu(object):
    def setupUi(self, New_Stu):
        New_Stu.setObjectName("New_Stu")
        New_Stu.resize(554, 249)
        font = QtGui.QFont()
        font.setPointSize(12)
        New_Stu.setFont(font)
        self.verticalLayoutWidget = QtWidgets.QWidget(New_Stu)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 511, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 3, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_error = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_error.setEnabled(True)
        self.label_error.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("color: red;")
        self.label_error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_error.setWordWrap(True)
        self.label_error.setObjectName("label_error")
        self.verticalLayout.addWidget(self.label_error, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(New_Stu)
        self.pushButton.clicked.connect(New_Stu.button_ok) # type: ignore
        New_Stu.set_name['QString'].connect(self.lineEdit.setText) # type: ignore
        New_Stu.set_id['QString'].connect(self.lineEdit_2.setText) # type: ignore
        self.pushButton_2.clicked.connect(New_Stu.close) # type: ignore
        New_Stu.set_github['QString'].connect(self.lineEdit_3.setText) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(New_Stu)
        New_Stu.setTabOrder(self.lineEdit, self.lineEdit_2)
        New_Stu.setTabOrder(self.lineEdit_2, self.lineEdit_3)
        New_Stu.setTabOrder(self.lineEdit_3, self.pushButton)
        New_Stu.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, New_Stu):
        _translate = QtCore.QCoreApplication.translate
        New_Stu.setWindowTitle(_translate("New_Stu", "New Student"))
        self.label_3.setText(_translate("New_Stu", "Setting Your Info"))
        self.lineEdit.setPlaceholderText(_translate("New_Stu", "Esmail Mahjoor"))
        self.lineEdit_2.setPlaceholderText(_translate("New_Stu", "973112030"))
        self.label_2.setText(_translate("New_Stu", "Id"))
        self.label.setText(_translate("New_Stu", "Full Name"))
        self.label_4.setText(_translate("New_Stu", "Github Id"))
        self.lineEdit_3.setPlaceholderText(_translate("New_Stu", "smal1378"))
        self.pushButton_2.setText(_translate("New_Stu", "Cancel"))
        self.pushButton.setText(_translate("New_Stu", "Okay"))
        self.label_error.setText(_translate("New_Stu", "Error Here"))
